# Generated by Django 3.2.7 on 2021-09-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_name_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Desc',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
