# Generated by Django 3.2.7 on 2021-09-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
